---
config :   'l33'
linelist : '20200709'
wrange :   [15100.,17000.]
continuum :    [4.00,1.00,0.00,0.00]
npart :     12
maskdir :   filters_CeNdYbC13
apred :     r12
telescope : apo25m
lsfid :     14600018
waveid :    13140000

defaults : &defaults
    synthcode : synspec
    atmos : marcs
    r0 : 1
    dw : 0.05
    vmacrofit : 1
    vmacro : [0.470794,0.,0.,-0.254120]
    vmicrofit : 0
    vmicro : [0.372160,-0.090531,-0.000802,0.001263,-0.027321]
    elem : ['']

giant: &giant
    <<: *defaults
    mh0 : -2.5
    dmh : 1
    nmh : 4
    am0 : 0
    dam : 0.25
    nam : 1
    cm0 : 0
    dcm : 0.25
    ncm : 1
    nm0 : 0
    dnm : 0.5
    nnm : 1
    vt0 : 0.0791812
    dvt : 0.301030
    nvt : 1
    rot0 : 0.176091
    drot : 0.301030
    nrot : 1
    kernel : gauss
    npca : 75
    solarisotopes : 2
dwarf: &dwarf
    <<: *defaults
    mh0 : -2.5
    dmh : 1
    nmh : 4
    am0 : 0
    dam : 0.25
    nam : 1
    cm0 : 0
    dcm : 0.25
    ncm : 1
    nm0 : 0
    dnm : 0.5
    nnm : 1
    vt0 : 0.0791812
    dvt : 0.301030
    nvt : 1
    rot0 : 0.176091
    drot : 0.301030
    nrot : 1
    kernel : rot
    npca : 75
    solarisotopes : 1

GKg : &GKg
    <<: *giant
    specdir : testGKg
    teff0 : 3500
    dteff : 1000
    nteff : 3
    logg0 : 0
    dlogg : 2
    nlogg : 2
Mg : &Mg
    <<: *giant
    specdir : testMg
    teff0 : 3000
    dteff : 500
    nteff : 3
    logg0 : -0.5
    dlogg : 2
    nlogg : 3
Fd: &Fd
    <<: *dwarf
    specdir : testFd
    solarisotopes : 1
    teff0 : 5500
    dteff : 1000
    nteff : 3
    logg0 : 2.5
    dlogg : 1.0
    nlogg : 3
GKd: &GKd
    <<: *dwarf
    specdir : testGKd
    solarisotopes : 1
    teff0 : 3500
    dteff : 1000
    nteff : 3
    logg0 : 2.5
    dlogg : 1
    nlogg : 3
Md: &Md
    <<: *dwarf
    specdir : testMd
    teff0 : 3000
    dteff : 500
    nteff : 3
    logg0 : 2.5
    dlogg : 1.5
    nlogg : 3

lsfcombo: &lsfcombo
    smooth : lsfcombo5_l33
    suffix : l33
    lsffiber : [50,100,150,200,250]
lsfa: &lsfa
    smooth : lsfa_l33
    suffix : l33
    lsffiber : [266,272,280,288,296]
lsfb: &lsfb
    smooth : lsfb_l33
    suffix : l33
    lsffiber : [160,183,206,228,250]
lsfc: &lsfc
    smooth : lsfc_l33
    suffix : l33
    lsffiber : [60,80,100,119,140]
lsfd: &lsfd
    smooth : lsfd_l33
    suffix : l33
    lsffiber : [5,15,25,35,45]
GRID :
  - <<: *GKg
    <<: *lsfcombo 
  - <<: *Mg
    <<: *lsfcombo 
  - <<: *Fd
    <<: *lsfcombo 
  - <<: *GKd
    <<: *lsfcombo 
  - <<: *Md
    <<: *lsfcombo 

