---
lsfcombo5 : &lsfcombo5
    fibermin : 0
    fibermax : 300

defaults : &defaults
    mask :  dr17/global_mask_v02.txt
    windows : dr17/
    inter :           3
    renorm :          -4
    obscont :    1
    rejectcont :    0.30
    algor : 3

dwarf : &dwarf
    <<: *defaults
    nov  :      8
    indv :  [1,2,3,4,5,6,7,8]
    indini : [ -1,-1,-1,-1,-1,-1,-1,-1]
    initpar : [0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.000]

giant : &giant
    <<: *defaults
    nov  :      7
    indv :  [1,2,3,4,5,6,7]
    indini : [ -1,-1,-1,-1,-1,-1,-1]
    initpar : [0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000]

GK : &GK
    holefile : marcs/MARCS_v3_2016/MARCS_GK_holefile.fits
    init : 1 
    teff_range :    [3500.,6000.]

GKg: &GKg
    <<: *GK
    <<: *giant
    logg_range :    [-10.,4.0]
    PLOCK :
      - name : LGVSINI 
        const : 0.4708
        te_coef : 0.000
        logg_coef : [0.,0.,0.] 
        mh_coef : -0.2541
      - name : O
        const : 0.000
        te_coef : 0.000
        logg_coef : [0.,0.,0.] 
        mh_coef : 0.000
   
GKd: &GKd
    <<: *GK
    <<: *dwarf
    logg_range :    [3.5,10]
    PLOCK :
      - name : O
        const : 0.000
        te_coef : 0.000
        logg_coef : [0.,0.,0.] 
        mh_coef : 0.000
   
M : &M
    holefile : marcs/MARCS_v3_2016/MARCS_M_holefile.fits
    init : 1 
    teff_range :    [2500.,4500.]

Mg : &Mg
    << :  *M
    << : *giant
    logg_range :    [-10.,4.0]
    PLOCK :
      - name : LGVSINI 
        const : 0.4708
        te_coef : 0.000
        logg_coef : [0.,0.,0.] 
        mh_coef : -0.2541
      - name : O
        const : 0.000
        te_coef : 0.000
        logg_coef : [0.,0.,0.] 
        mh_coef : 0.000

Md : &Md
    << : *M
    << : *dwarf
    logg_range :    [3.5,10]
    PLOCK :
      - name : O
        const : 0.000
        te_coef : 0.000
        logg_coef : [0.,0.,0.] 
        mh_coef : 0.000

F : &F
    holefile : marcs/MARCS_v3_2016/MARCS_F_holefile.fits
    init : 1 
    teff_range :    [5000.,8500.]

Fd : &Fd
    << : *F
    << : *dwarf
    logg_range :    [-10.,10.]
    PLOCK :
      - name : O
        const : 0.000
        te_coef : 0.000
        logg_coef : [0.,0.,0.] 
        mh_coef : 0.000

grids :
  - name : GKg
    lib : turbospec/marcs/giantisotopes/tgGK_180901_l33_lsfcombo5s/p_apstgGK_180901_l33_lsfcombo5s_012_075
    <<: *GKg
    <<: *lsfcombo5
  - name : GKd
    lib : turbospec/marcs/solarisotopes/tdGK_180901_l33_lsfcombo5s/p_apstdGK_180901_l33_lsfcombo5s_012_075
    <<: *GKd
    <<: *lsfcombo5
  - name : Mg
    lib : turbospec/marcs/giantisotopes/tgM_180901_dr17_lsfcombo5s/p_apstgM_180901_dr17_lsfcombo5s_012_075
    <<: *Mg
    <<: *lsfcombo5
  - name : Md
    lib : turbospec/marcs/solarisotopes/tdM_180901_l33_lsfcombo5s/p_apstdM_180901_l33_lsfcombo5s_012_075
    <<: *Md
    <<: *lsfcombo5
  - name : Fd
    lib : turbospec/marcs/solarisotopes/tdF_180901_l33_lsfcombo5s/p_apstdF_180901_l33_lsfcombo5s_012_075
    <<: *Fd
    <<: *lsfcombo5

elems :
    - name : C
      griddim : 'C'
    - name : CI
      griddim : 'C'
    - name : N
      griddim : 'N'
    - name : O
      griddim : 'O Mg Si S Ca Ti'
    - name : Na
      griddim : 'METALS'
    - name : Mg
      griddim : 'O Mg Si S Ca Ti'
    - name : Al
      griddim : 'METALS'
    - name : Si
      griddim : 'O Mg Si S Ca Ti'
    - name : P
      griddim : 'METALS'
    - name : S
      griddim : 'O Mg Si S Ca Ti'
    - name : K
      griddim : 'METALS'
    - name : Ca
      griddim : 'O Mg Si S Ca Ti'
    - name : Ti
      griddim : 'O Mg Si S Ca Ti'
    - name : TiII
      griddim : 'O Mg Si S Ca Ti'
    - name : V
      griddim : 'METALS'
    - name : Cr
      griddim : 'METALS'
    - name : Mn
      griddim : 'METALS'
    - name : Fe
      griddim : 'METALS'
    - name : Co
      griddim : 'METALS'
    - name : Ni
      griddim : 'METALS'
    - name : Cu
      griddim : 'METALS'
    - name : Ce
      griddim : 'METALS'
    - name : Nd
      griddim : 'METALS'
